services:
  database:
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=examplepassword
    expose:
      - 5432
    healthcheck:
      interval: 10s
      retries: 5
      test: [ "CMD", "pg_isready" ]
      timeout: 5s
    image: library/postgres:15
    ports:
      - 5432:5432
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

version: '3'

volumes:
  db-data:
